import { createWasmKernel } from "../src/wasm-kernel.js";
import { readFileSync } from "fs";
const DIR = process.env.OCJS_DIR || "/tmp/oc/rep/package/dist";
const initModule = (await import(DIR + "/replicad_single.js")).default;
const kernel = await createWasmKernel({ initModule, wasmBinary: readFileSync(DIR + "/replicad_single.wasm") });
let failures = 0;
const check = (n, ok, d = "") => { if (!ok) failures++; console.log((ok ? "  ok   " : "  FAIL ") + n + (d ? "  — " + d : "")); };

await kernel.loadModel({ format: "ocaf-parametric-model", version: 1, name: "Heydar", units: "mm", features: [] });
let t = Date.now();
let out = await kernel.addFeature("Center", {});
console.log("  built in", Date.now() - t, "ms");
check("it built", out.report.failed.length === 0, JSON.stringify(out.report.failed.map(f => f.message)));
const id = out.id;
t = Date.now();
let mesh = (await kernel.mesh([id])).features[0];
console.log("  meshed in", Date.now() - t, "ms  ", mesh.triangles, "triangles");
check("it is real geometry", mesh.triangles > 2000, String(mesh.triangles));
t = Date.now();
out = await kernel.setParameter(id, "lobes", 4);
console.log("  lobes rebuilt in", Date.now() - t, "ms");
check("lobes rebuild", out.report.failed.length === 0, JSON.stringify(out.report.failed.map(f=>f.message)));
out = await kernel.setParameter(id, "facade", 1);
check("the facade switches off", out.report.failed.length === 0);
const bare = (await kernel.mesh([id])).features[0].triangles;
out = await kernel.setParameter(id, "facade", 0);
check("and back on, with more geometry", (await kernel.mesh([id])).features[0].triangles > bare);
console.log(failures ? "\n" + failures + " failed" : "\nall checks passed");
process.exit(failures ? 1 : 0);
