"""Subset DejaVu Sans to the WinAnsi (cp1252) repertoire and write src/fontdata.js.

The same bytes are embedded in every PDF (FontFile2, subset-tagged) and served
to the canvas as an @font-face, so screen text and paper text have identical
metrics - a title block that reflows is a drawing lying about its revision (§12.3).
Run once: python3 tools/make_font.py  (needs fonttools; DejaVu is Bitstream Vera-licensed)."""
import base64, io, json, sys
from fontTools.ttLib import TTFont
from fontTools import subset

SRC = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
codes = {}
for b in range(32, 256):
    try:
        ch = bytes([b]).decode("cp1252")
    except UnicodeDecodeError:
        continue
    codes[b] = ch
opts = subset.Options()
opts.layout_features = []
opts.name_IDs = ["*"]
opts.notdef_outline = True
opts.hinting = False
opts.desubroutinize = True
font = TTFont(SRC)
sub = subset.Subsetter(opts)
sub.populate(unicodes=[ord(c) for c in codes.values()])
sub.subset(font)
buf = io.BytesIO(); font.save(buf); data = buf.getvalue()
cmap = font.getBestCmap(); hmtx = font["hmtx"]; upm = font["head"].unitsPerEm
widths = {}
for b, ch in codes.items():
    g = cmap.get(ord(ch))
    widths[b] = round(hmtx[g][0] * 1000 / upm) if g else 0
os2 = font["OS/2"]; head = font["head"]; hhea = font["hhea"]
metrics = {
    "unitsPerEm": upm, "ascent": round(hhea.ascent * 1000 / upm), "descent": round(hhea.descent * 1000 / upm),
    # OS/2 v1 (DejaVu) has no sCapHeight: measure the capital H instead. Getting
    # this wrong scales every text on screen and paper by the same wrong factor.
    "capHeight": round((getattr(os2, "sCapHeight", 0) or font["glyf"][cmap[ord("H")]].yMax) * 1000 / upm),
    "bbox": [round(v * 1000 / upm) for v in (head.xMin, head.yMin, head.xMax, head.yMax)],
    "unicodeToCode": {ord(ch): b for b, ch in codes.items()},
}
out = sys.argv[1] if len(sys.argv) > 1 else "src/fontdata.js"
with open(out, "w") as f:
    f.write("//! Generated by tools/make_font.py - DejaVu Sans subset to cp1252 (Bitstream Vera licence).\n")
    f.write("//! One font for screen and paper: widths in 1/1000 em by WinAnsi code.\n")
    f.write("export const FONT_NAME = \"DejaVuSans\";\n")
    f.write("export const FONT_WIDTHS = " + json.dumps(widths, separators=(",", ":")) + ";\n")
    f.write("export const FONT_METRICS = " + json.dumps(metrics, separators=(",", ":")) + ";\n")
    f.write("export const FONT_TTF_B64 = \"" + base64.b64encode(data).decode() + "\";\n")
print(out, len(data), "bytes of TTF,", len(widths), "codes")
